### ISSUE TITLE
Add to TODO

### ISSUE THREAD

**Issue by peymet200** [peymet200/HorseWorld#2]
- [x] add new font styles for design sys info the master file 
- [x] upload new arrow element to files 
- [x] document notes on the design guidelines
